# Settings
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g visual-activity off
bind r source-file ~/.tmux.conf

# Terminal
bind -n M-r send-keys reset Enter

# Panes
set -g @vim_navigator_prefix_mapping_clear_screen ""
set -g @vim_navigator_mapping_prev ""
bind -n M-/ split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"
bind -n M-enter resize-pane -Z
bind -nr C-S-h resize-pane -L 5
bind -nr C-S-j resize-pane -D 5
bind -nr C-S-k resize-pane -U 5
bind -nr C-S-l resize-pane -R 5
bind -n M-p command-prompt -p "Send pane to:" "join-pane -t '%%'"

# Windows
bind -n M-l next-window
bind -n M-h previous-window
bind -n M-H swap-window -d -t -1
bind -n M-L swap-window -d -t +1

# Sessions
bind -n M-k switch-client -p
bind -n M-j switch-client -n

# Yazi
set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Theme
set -g status-position top
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true
set -g @dracula-show-left-icon " #S"
set -g @dracula-left-icon-padding 0
set -g @dracula-plugins "cwd weather tmux-ram-usage"
set -g @dracula-tmux-ram-usage-label " "
set -g @dracula-show-location false

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "dracula/tmux"

# Initialize tmux plugin manager
run "~/.tmux/plugins/tpm/tpm"
